# Generated by Django 2.2.3 on 2019-07-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190707_1505'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
