# Generated by Django 2.2.3 on 2019-07-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='token',
            field=models.CharField(default=11111111111111111111111111111, max_length=40, verbose_name='Ключ'),
            preserve_default=False,
        ),
    ]
